In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a.shape

(6,)

In [7]:
b = a.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c = np.array([1,2,3,4,5,6])
d = np.array([1,2,3,4,5,6])

In [24]:
# 浅いコピー
r_c = c.ravel()
# 深いコピー
f_d = d.flatten()

In [25]:
r_c

array([10,  2,  3,  4,  5,  6])

In [26]:
f_d

array([1, 2, 3, 4, 5, 6])

In [27]:
r_c[0] = 10
f_d[0] = 10

In [28]:
c

array([10,  2,  3,  4,  5,  6])

In [29]:
d

array([1, 2, 3, 4, 5, 6])

In [30]:
np.random.seed(123)
np.random.uniform(0.0, 10.0, size=(5,6))

array([[6.96469186, 2.86139335, 2.26851454, 5.51314769, 7.1946897 ,
        4.2310646 ],
       [9.80764198, 6.84829739, 4.80931901, 3.92117518, 3.43178016,
        7.29049707],
       [4.38572245, 0.59677897, 3.98044255, 7.37995406, 1.8249173 ,
        1.75451756],
       [5.31551374, 5.31827587, 6.34400959, 8.49431794, 7.24455325,
        6.11023511],
       [7.22443383, 3.22958914, 3.61788656, 2.28263231, 2.93714046,
        6.30976124]])

In [31]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
e = np.array([[1,2,3], [4,5,6]])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
e.T

array([[1, 4],
       [2, 5],
       [3, 6]])